version: "3.9"
services:
  proxy:
    container_name: fullstack-proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html

  app:
    container_name: fullstack-app
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html

  db:
    container_name: fullstack-db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - fullstack-db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: fullstack-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ROOT_PASSWORD=rootpassword

volumes:
  fullstack-db-volume:
