version: "3.9"
services:
  proxy:
    container_name: fullstack-proxy
    build: ./docker/nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html

  # app:
  #   build: ./docker/php
